// This file is generated by bun run build:icons

export type IconList =
	| "mdi:at"
	| "mdi:github"
	| "mdi:linkedin"
	| "mdi:twitter"
	| "lucide:arrow-up-right"
	| "lucide:chevron-left"
	| "lucide:chevron-right"
